export const ROUTES = {
  splash: '/',
  language: '/language',
  login: '/login',
  home: '/(tabs)',
  crop: '/(tabs)/crop',
  weather: '/weather',
  mandiRates: '/mandi-rates',
  cropProtection: '/crop-protection',
  fertilizers: '/fertilizers',
  pesticides: '/pesticides',
  fungicides: '/fungicides',
  ai: '/(tabs)/ai',
  aiChat: '/(tabs)/ai/[id]',
  profile: '/(tabs)/profile',
  settings: '/settings',
  about: '/about',
  privacy: '/privacy',
  terms: '/terms',
  cropGuide: '/(tabs)/crop',
} as const;
