import {
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core';

/** Unified agriculture product catalog — fertilizers, pesticides, fungicides, herbicides */
export const agProducts = pgTable(
  'ag_products',
  {
    id: varchar('id', { length: 120 }).primaryKey(),
    name: varchar('name', { length: 200 }).notNull(),
    nameTe: varchar('name_te', { length: 200 }),
    type: varchar('type', { length: 40 }).notNull(),
    subType: varchar('sub_type', { length: 60 }),
    brand: varchar('brand', { length: 120 }),
    activeIngredient: varchar('active_ingredient', { length: 200 }),
    nutrientComposition: text('nutrient_composition'),
    npkRatio: varchar('npk_ratio', { length: 40 }),
    dosage: varchar('dosage', { length: 200 }).notNull(),
    crops: jsonb('crops').$type<string[]>().notNull().default([]),
    soilTypes: jsonb('soil_types').$type<string[]>().notNull().default([]),
    growthStages: jsonb('growth_stages').$type<string[]>().notNull().default([]),
    deficiencySymptoms: jsonb('deficiency_symptoms').$type<string[]>().default([]),
    targetPest: varchar('target_pest', { length: 200 }),
    targetDisease: varchar('target_disease', { length: 200 }),
    applicationMethod: text('application_method'),
    precautions: text('precautions'),
    description: text('description'),
    price: varchar('price', { length: 80 }),
    image: varchar('image', { length: 200 }),
    source: varchar('source', { length: 40 }).notNull(),
    sourceUrl: text('source_url'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ag_products_type_idx').on(t.type),
    index('ag_products_sub_type_idx').on(t.subType),
    index('ag_products_brand_idx').on(t.brand),
    index('ag_products_name_idx').on(t.name),
  ],
);

/** Expanded crop disease catalog (2000+) with symptoms & treatment */
export const cropDiseaseCatalog = pgTable(
  'crop_disease_catalog',
  {
    id: varchar('id', { length: 120 }).primaryKey(),
    name: varchar('name', { length: 200 }).notNull(),
    nameTe: varchar('name_te', { length: 200 }),
    cropId: varchar('crop_id', { length: 40 }).notNull(),
    category: varchar('category', { length: 40 }).notNull(),
    pathogen: varchar('pathogen', { length: 200 }),
    symptoms: text('symptoms').notNull(),
    deficiencySymptoms: jsonb('deficiency_symptoms').$type<string[]>().default([]),
    treatment: text('treatment'),
    prevention: text('prevention'),
    growthStage: varchar('growth_stage', { length: 60 }),
    soilTypes: jsonb('soil_types').$type<string[]>().default([]),
    image: varchar('image', { length: 200 }),
    source: varchar('source', { length: 40 }).notNull(),
    sourceUrl: text('source_url'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('crop_disease_catalog_crop_idx').on(t.cropId),
    index('crop_disease_catalog_category_idx').on(t.category),
    index('crop_disease_catalog_name_idx').on(t.name),
  ],
);
