import type { CropVariety } from '@/types/cropVariety';

export const CURATED_VARIETIES: Record<string, CropVariety[]> = {
  rice: [
    {
      id: 'sona_masoori',
      cropId: 'rice',
      name: 'Sona Masoori (BPT 5204)',
      nameTe: 'సోనా మసూరి (BPT 5204)',
      aliases: ['masoori', 'masuri', 'sona masoori', 'bpt 5204', 'bpt5204'],
      agmarknetNames: ['BPT 5204', 'Sona Masoori', 'BPT-5204', 'Fine'],
      duration: '125–135 days',
      grainType: 'Fine / soft cooking',
      yieldPotential: '18–22 quintals/acre',
      sowingWindow: 'Jun–Jul (Kharif), Nov–Dec (Rabi)',
      harvestWindow: 'Oct–Nov / Mar–Apr',
      referenceBaselineQtl: 2280,
      priceNote: 'Premium fine rice — usually ₹150–350/qtl above common paddy',
      priceNoteTe: 'Fine rice premium — sadharana vari kante ekkuva rate',
      seedRate: '8–10 kg/acre (transplant)',
      fertilizerNotes: [
        'Split urea: 40 kg at tillering + 30 kg at panicle initiation',
        'Zinc sulphate 25 kg/acre if deficiency — critical for fine grain filling',
        'Avoid excess N after flowering — chalkiness increases in BPT',
      ],
      fertilizerNotesTe: [
        'Urea rendu sarlu: tillering + panicle initiation',
        'Zinc lekapothe 25 kg/acre — grain filling ki mukhyam',
        'Flowering tarvata ekkuva nitrogen vaddu',
      ],
      sprayNotes: [
        'Blast sensitive at neck — Tricyclazole at panicle emergence mandatory in humid zones',
        'BPH monitoring weekly from tillering — Imidacloprid only at ETL',
      ],
      sprayNotesTe: [
        'Blast ki panicle time Tricyclazole avasaram',
        'BPH tillering nunche weekly chudandi',
      ],
      diseaseSusceptibility: ['Blast (high)', 'BPH', 'Sheath blight'],
      specialCare: ['Maintain 5 cm water at tillering', 'Harvest at 80% golden grains'],
      specialCareTe: ['Tillering lo 5 cm neeru', '80% golden ayyaka harvest'],
    },
    {
      id: 'mtu_1010',
      cropId: 'rice',
      name: 'MTU 1010',
      nameTe: 'MTU 1010 (1010)',
      aliases: ['1010', 'mtu1010', 'mtu 1010', 'ten ten'],
      agmarknetNames: ['1010', 'MTU 1010', 'MTU-1010', 'MTU1010'],
      duration: '115–125 days',
      grainType: 'Medium fine',
      yieldPotential: '20–25 quintals/acre',
      sowingWindow: 'Jun–Jul',
      harvestWindow: 'Oct–Nov',
      referenceBaselineQtl: 2150,
      priceNote: 'Popular medium variety — moderate premium over common paddy',
      priceNoteTe: 'Chala popular variety — madhya range rate',
      seedRate: '8–10 kg/acre',
      fertilizerNotes: [
        'Basal DAP 40 kg + urea 40+30 kg split',
        'Potassium 15 kg/acre at panicle if soil tests low K',
      ],
      fertilizerNotesTe: ['DAP basal, urea split doses', 'Panicle time potassium avasaramaina'],
      sprayNotes: [
        'Stem borer whorl stage — Cartap hydrochloride or chlorantraniliprole',
        'Leaf folder — neem 1% preventive at tillering',
      ],
      sprayNotesTe: ['Stem borer ki whorl stage spray', 'Leaf folder ki neem preventive'],
      diseaseSusceptibility: ['Stem borer', 'Leaf folder', 'BPH'],
      specialCare: ['Good for Telangana medium lands', 'Transplant 21–25 day old seedlings'],
      specialCareTe: ['Telangana medium lands ki baguntundi', '21–25 roju seedlings transplant'],
    },
    {
      id: 'sugarfree',
      cropId: 'rice',
      name: 'Sugarfree / Low GI (668)',
      nameTe: 'Sugarfree / Low GI (668)',
      aliases: ['sugarfree', 'sugarless', 'sugar free', '668', 'diabetic rice', 'low gi'],
      agmarknetNames: ['668', 'Sugar Free', 'Sugarfree', 'DRR Dhan 48'],
      duration: '130–140 days',
      grainType: 'Low glycemic index — specialty',
      yieldPotential: '16–20 quintals/acre',
      sowingWindow: 'Jun–Jul',
      harvestWindow: 'Nov–Dec',
      referenceBaselineQtl: 2450,
      priceNote: 'Specialty diabetic rice — ₹300–600/qtl premium; niche market demand',
      priceNoteTe: 'Diabetic rice — chala premium rate, niche market',
      seedRate: '8 kg/acre — use certified seed only',
      fertilizerNotes: [
        'Balanced NPK — avoid excess nitrogen (reduces grain quality)',
        'Organic matter + zinc for specialty grain filling',
        'Foliar micronutrients at flowering',
      ],
      fertilizerNotesTe: [
        'Balanced NPK — ekkuva nitrogen vaddu',
        'Organic matter + zinc',
        'Flowering lo foliar micronutrients',
      ],
      sprayNotes: [
        'Strict IPM — chemical residues affect specialty market price',
        'Neem-based first, chemicals only at ETL with full PHI compliance',
      ],
      sprayNotesTe: [
        'IPM follow cheyandi — residue unte rate taggutundi',
        'Mundu neem, tarvata chemicals ETL prakaram',
      ],
      diseaseSusceptibility: ['Blast', 'Brown spot'],
      specialCare: [
        'Target health food / diabetic market — quality over quantity',
        'Separate storage from common rice to avoid mixing',
      ],
      specialCareTe: [
        'Health market kosam — quality mukhyam',
        'Veri rice tho kalipokunda separate storage',
      ],
    },
    {
      id: 'swarna',
      cropId: 'rice',
      name: 'Swarna (MTU 7029)',
      nameTe: 'Swarna (MTU 7029)',
      aliases: ['swarna', 'mtu 7029', '7029'],
      agmarknetNames: ['Swarna', 'MTU 7029', 'MTU-7029'],
      duration: '135–145 days',
      grainType: 'Medium bold — high yielding',
      yieldPotential: '24–28 quintals/acre',
      sowingWindow: 'Jun–Jul',
      harvestWindow: 'Nov–Dec',
      referenceBaselineQtl: 2050,
      priceNote: 'High yield variety — rate usually slightly below fine rice',
      priceNoteTe: 'Yield ekkuva — fine rice kante konchem tagina rate',
      seedRate: '8–10 kg/acre',
      fertilizerNotes: [
        'Higher total N needed for yield: 100–120 kg N/acre in splits',
        'Silicon + potassium at booting for lodging resistance',
      ],
      fertilizerNotesTe: ['Yield kosam N ekkuva — splits lo', 'Booting lo K + silicon'],
      sprayNotes: [
        'Sheath blight common in dense crop — Validamycin at ETL',
        'Plan harvest early if lodging risk',
      ],
      sprayNotesTe: ['Sheath blight — Validamycin', 'Lodging unte tondaraga harvest'],
      diseaseSusceptibility: ['Sheath blight', 'BPH', 'Case worm'],
      specialCare: ['Wide spacing if using high N', 'Monitor lodging at maturity'],
      specialCareTe: ['Spacing penchandi high N unte', 'Maturity lo lodging chudandi'],
    },
    {
      id: 'rnr_15048',
      cropId: 'rice',
      name: 'RNR 15048 (Fine)',
      nameTe: 'RNR 15048',
      aliases: ['rnr 15048', 'rnr15048', '15048'],
      agmarknetNames: ['RNR 15048', 'RNR-15048', '15048'],
      duration: '120–130 days',
      grainType: 'Fine — popular in AP/Telangana',
      yieldPotential: '20–24 quintals/acre',
      sowingWindow: 'Jun–Jul, Nov–Dec',
      harvestWindow: 'Oct–Nov / Mar–Apr',
      referenceBaselineQtl: 2220,
      priceNote: 'Fine rice — good mill outturn, steady mandi demand',
      priceNoteTe: 'Fine rice — mill outturn bagundi, mandi demand steady',
      seedRate: '8–10 kg/acre',
      fertilizerNotes: [
        'Standard NPK for fine rice with zinc at tillering',
        'Second urea at panicle initiation critical for head rice recovery',
      ],
      fertilizerNotesTe: ['Fine rice NPK + zinc tillering', 'Panicle time 2nd urea mukhyam'],
      sprayNotes: [
        'Blast on neck — 2 sprays Tricyclazole if weather humid',
        'False smut — avoid excess N + timely harvest',
      ],
      sprayNotesTe: ['Blast ki Tricyclazole 2 sarlu', 'False smut — ekkuva N vaddu'],
      diseaseSusceptibility: ['Blast', 'False smut', 'BPH'],
      specialCare: ['Popular for parboiling and raw rice mills'],
      specialCareTe: ['Parboiling mills ki popular'],
    },
    {
      id: 'tellahamsa',
      cropId: 'rice',
      name: 'Tellahamsa',
      nameTe: 'తెల్లహంస',
      aliases: ['tellahamsa', 'tella hamsa', 'white swan'],
      agmarknetNames: ['Tellahamsa', 'Tella Hamsa'],
      duration: '125–135 days',
      grainType: 'Fine aromatic tendency',
      yieldPotential: '18–22 quintals/acre',
      sowingWindow: 'Jun–Jul',
      harvestWindow: 'Oct–Nov',
      referenceBaselineQtl: 2180,
      priceNote: 'Local fine variety — price follows fine rice segment',
      priceNoteTe: 'Local fine variety — fine rice rate laga untundi',
      seedRate: '8 kg/acre',
      fertilizerNotes: [
        'Moderate N with organic manure basal improves aroma',
        'Zinc at tillering',
      ],
      fertilizerNotesTe: ['Organic manure basal — aroma ki', 'Zinc tillering'],
      sprayNotes: [
        'Standard IPM for fine rice',
        'Avoid broad-spectrum sprays near harvest',
      ],
      sprayNotesTe: ['Fine rice IPM follow', 'Harvest daggara spray vaddu'],
      diseaseSusceptibility: ['Blast', 'Leaf blast'],
      specialCare: ['Maintain field hygiene for quality'],
      specialCareTe: ['Field clean ga unchaali quality kosam'],
    },
  ],

  wheat: [
    {
      id: 'hd_3086',
      cropId: 'wheat',
      name: 'HD 3086',
      nameTe: 'HD 3086',
      aliases: ['hd3086', 'hd 3086'],
      agmarknetNames: ['HD 3086', 'HD-3086', 'Wheat HD 3086'],
      duration: '110–120 days',
      grainType: 'Medium bold — irrigated',
      yieldPotential: '18–22 quintals/acre',
      sowingWindow: 'Oct–Nov (timely sowing)',
      harvestWindow: 'Mar–Apr',
      referenceBaselineQtl: 2300,
      priceNote: 'Popular North India variety — mandi rate near MSP in harvest season',
      priceNoteTe: 'North India lo popular — harvest season lo MSP daggara',
      seedRate: '40–50 kg/acre',
      fertilizerNotes: [
        '120 kg N/acre in 3 splits: basal, CRI (21 DAS), flowering',
        'Full dose DAP 50 kg + MOP 25 kg at sowing',
        'Second irrigation at crown root initiation (21 DAS) critical',
      ],
      fertilizerNotesTe: [
        'N 3 sarlu: basal, CRI, flowering',
        'DAP + MOP sowing time lo',
        'CRI (21 roju) neeru mukhyam',
      ],
      sprayNotes: [
        'Yellow rust — Propiconazole at first stripe appearance',
        'Broadleaf weeds — Metsulfuron at 30–35 DAS on clear day',
      ],
      sprayNotesTe: [
        'Yellow rust ki Propiconazole',
        '30–35 DAS weed control Metsulfuron',
      ],
      diseaseSusceptibility: ['Yellow rust', 'Karnal bunt', 'Powdery mildew'],
      specialCare: ['Sow before mid-November for best yield', 'Avoid late sowing in warm winters'],
      specialCareTe: ['Nov madhyalo kante mundu sowing', 'Late sowing vaddu'],
    },
    {
      id: 'pbw_343',
      cropId: 'wheat',
      name: 'PBW 343',
      nameTe: 'PBW 343',
      aliases: ['pbw343', 'pbw 343'],
      agmarknetNames: ['PBW 343', 'PBW-343', 'Wheat PBW 343'],
      duration: '115–125 days',
      grainType: 'Medium bold — high yielding',
      yieldPotential: '20–24 quintals/acre',
      sowingWindow: 'Oct–Nov',
      harvestWindow: 'Mar–Apr',
      referenceBaselineQtl: 2280,
      priceNote: 'Punjab/Haryana staple — trades at MSP; protein content affects mill premium',
      priceNoteTe: 'Punjab/Haryana lo staple — MSP rate, protein batti premium',
      seedRate: '40–45 kg/acre',
      fertilizerNotes: [
        '130 kg N/acre for high yield potential in 3 splits',
        'Zinc sulphate 10 kg/acre if soil deficient',
        'Irrigation at CRI, tillering, and flowering',
      ],
      fertilizerNotesTe: [
        'Yield kosam N 130 kg — 3 splits',
        'Zinc lekapothe 10 kg/acre',
        'CRI, tillering, flowering neeru',
      ],
      sprayNotes: [
        'Loose smut — Vitavax/Carboxin seed treatment mandatory',
        'Aphids at earhead — Dimethoate at ETL only',
      ],
      sprayNotesTe: [
        'Loose smut ki seed treatment avasaram',
        'Earhead aphids ETL prakaram Dimethoate',
      ],
      diseaseSusceptibility: ['Loose smut', 'Yellow rust', 'Aphids'],
      specialCare: ['Use certified seed every season', 'Monitor rust in humid Feb–Mar'],
      specialCareTe: ['Certified seed use cheyandi', 'Feb–Mar rust chudandi'],
    },
    {
      id: 'wh_1105',
      cropId: 'wheat',
      name: 'WH 1105',
      nameTe: 'WH 1105',
      aliases: ['wh1105', 'wh 1105'],
      agmarknetNames: ['WH 1105', 'WH-1105', 'Wheat WH 1105'],
      duration: '105–115 days',
      grainType: 'Medium bold — early maturing',
      yieldPotential: '17–21 quintals/acre',
      sowingWindow: 'Nov (late-sown acceptable)',
      harvestWindow: 'Mar',
      referenceBaselineQtl: 2220,
      priceNote: 'Early variety — useful for late sowing; rate similar to common wheat',
      priceNoteTe: 'Early variety — late sowing ki baguntundi, normal wheat rate',
      seedRate: '45–50 kg/acre (higher for late sowing)',
      fertilizerNotes: [
        '100 kg N/acre — apply full basal if sowing late',
        'Increase seed rate by 10% for late-sown conditions',
      ],
      fertilizerNotesTe: [
        'Late sowing unte N basal ga ekkuva',
        'Seed rate 10% penchandi late sowing ki',
      ],
      sprayNotes: [
        'Terminal heat stress — foliar K at booting if Feb is warm',
        'Weed control within 30 DAS essential for late crop',
      ],
      sprayNotesTe: [
        'Heat stress unte booting lo foliar K',
        '30 DAS lopu weed control mukhyam',
      ],
      diseaseSusceptibility: ['Heat stress at grain fill', 'Yellow rust (moderate)'],
      specialCare: ['Best option when monsoon delays rabi sowing', 'Harvest promptly to avoid shattering'],
      specialCareTe: ['Late sowing ki best option', 'Shattering raku tondaraga harvest'],
    },
  ],

  cotton: [
    {
      id: 'bt_hybrid_bg2',
      cropId: 'cotton',
      name: 'Bt Cotton Hybrid (BG-II)',
      nameTe: 'Bt Cotton Hybrid (BG-II)',
      aliases: ['bt cotton', 'bg ii', 'bg2', 'bg-ii'],
      agmarknetNames: ['BT Cotton', 'Bt Cotton', 'Hybrid', 'Cotton Hybrid'],
      duration: '160–180 days',
      grainType: 'Long staple hybrid kapas',
      yieldPotential: '8–12 quintals/acre kapas',
      sowingWindow: 'May–Jun (Kharif)',
      harvestWindow: 'Oct–Jan (4–5 pickings)',
      referenceBaselineQtl: 6400,
      priceNote: 'Kapas rate varies by staple length (28–32 mm) and moisture',
      priceNoteTe: 'Staple length & moisture batti rate marutundi',
      seedRate: '400–600 g/acre (2–3 seeds/hill)',
      fertilizerNotes: [
        'Moderate N — 60–80 kg/acre; excess causes vegetative growth and delayed boll set',
        'MOP 15 kg/acre at square formation',
        'Foliar magnesium at boll filling if leaf yellowing',
      ],
      fertilizerNotesTe: [
        'N moderate — ekkuva unte leaves ekkuvavutayi',
        'Square time MOP 15 kg/acre',
        'Boll time magnesium foliar',
      ],
      sprayNotes: [
        'Pink bollworm resistance monitoring on BG-II — rotate chemistries (Emamectin, Spinosad)',
        'Whitefly at flowering — Pyriproxyfen IGR before peak',
        'Neem 1% at square stage for jassids/thrips',
      ],
      sprayNotesTe: [
        'Pink bollworm resistance chudandi — mandu rotate cheyandi',
        'Flowering lo whitefly ki Pyriproxyfen',
        'Square stage lo neem jassids ki',
      ],
      diseaseSusceptibility: ['Bollworm complex', 'Whitefly', 'Leaf curl virus'],
      specialCare: ['Refuge planting (non-Bt rows) mandatory', 'Pick when bolls fully open'],
      specialCareTe: ['Bt refuge planting cheyandi', 'Boll open ayyaka pick cheyandi'],
    },
    {
      id: 'rch_659',
      cropId: 'cotton',
      name: 'RCH 659 (Hybrid)',
      nameTe: 'RCH 659 Hybrid',
      aliases: ['rch659', 'rch 659'],
      agmarknetNames: ['RCH 659', 'RCH-659', 'RCH659'],
      duration: '150–170 days',
      grainType: 'Medium-long staple hybrid',
      yieldPotential: '10–14 quintals/acre kapas',
      sowingWindow: 'May–Jun',
      harvestWindow: 'Oct–Dec',
      referenceBaselineQtl: 6550,
      priceNote: 'High-yielding Gujarat/Maharashtra hybrid — premium for ginning outturn',
      priceNoteTe: 'Yield ekkuva hybrid — ginning outturn bagundi',
      seedRate: '450–550 g/acre',
      fertilizerNotes: [
        'Balanced NPK: 80 kg N + 40 kg P₂O₅ + 40 kg K₂O/acre',
        'Split N at square, flowering, and boll development',
        'Avoid top-dress N after 90 DAS',
      ],
      fertilizerNotesTe: [
        'Balanced NPK — N square, flowering, boll lo splits',
        '90 rojula tarvata N vaddu',
      ],
      sprayNotes: [
        'American bollworm — Emamectin at egg hatch on squares',
        'Sucking pests — Acetamiprid rotate with neem',
      ],
      sprayNotesTe: [
        'Bollworm ki Emamectin egg hatch time',
        'Sucking pests ki Acetamiprid/neem rotate',
      ],
      diseaseSusceptibility: ['American bollworm', 'Jassids', 'Alternaria leaf spot'],
      specialCare: ['Popular in irrigated black cotton soils', 'Maintain 90×60 cm or 120×60 cm spacing'],
      specialCareTe: ['Black cotton soils ki baguntundi', 'Spacing correct ga pettandi'],
    },
    {
      id: 'mrc_7031',
      cropId: 'cotton',
      name: 'MRC 7031 (Hybrid)',
      nameTe: 'MRC 7031 Hybrid',
      aliases: ['mrc7031', 'mrc 7031'],
      agmarknetNames: ['MRC 7031', 'MRC-7031', 'MRC7031'],
      duration: '155–175 days',
      grainType: 'Long staple — export quality tendency',
      yieldPotential: '9–13 quintals/acre kapas',
      sowingWindow: 'May–Jun',
      harvestWindow: 'Nov–Jan',
      referenceBaselineQtl: 6700,
      priceNote: 'Long staple hybrid — ₹100–200/qtl above medium staple in good years',
      priceNoteTe: 'Long staple — medium staple kante ekkuva rate',
      seedRate: '400–500 g/acre',
      fertilizerNotes: [
        'Moderate N with emphasis on K at boll fill — 70 kg N + 50 kg K₂O/acre',
        'Micronutrient spray (Zn + B) at flowering',
      ],
      fertilizerNotesTe: [
        'N moderate, K boll fill time ekkuva',
        'Flowering lo Zn + B foliar',
      ],
      sprayNotes: [
        'Follow IPM with pheromone traps for bollworm from 45 DAS',
        'Sticky cotton prevention — whitefly control before 3rd picking',
      ],
      sprayNotesTe: [
        '45 DAS nunche pheromone traps — IPM',
        '3rd picking mundu whitefly control',
      ],
      diseaseSusceptibility: ['Bollworm', 'Whitefly', 'Bacterial blight'],
      specialCare: ['Target export/long fibre markets', 'Timely defoliation before last picking if needed'],
      specialCareTe: ['Export market kosam', 'Last picking mundu defoliation avasaramaina'],
    },
  ],

  tomato: [
    {
      id: 'arka_rakshak',
      cropId: 'tomato',
      name: 'Arka Rakshak (Hybrid)',
      nameTe: 'Arka Rakshak Hybrid',
      aliases: ['arka rakshak', 'arkarakshak', 'rakshak'],
      agmarknetNames: ['Tomato Hybrid', 'Hybrid', 'Arka Rakshak'],
      duration: '90–110 days',
      grainType: 'Table hybrid — F1',
      yieldPotential: '150–200 quintals/acre',
      sowingWindow: 'Year-round nursery; avoid peak heat (Apr–May)',
      harvestWindow: '60–80 days post transplant',
      referenceBaselineQtl: 1950,
      priceNote: 'Hybrid tomato — rate driven by season more than variety; Rabi fetches premium',
      priceNoteTe: 'Hybrid tomato — season batti rate; Rabi lo premium',
      seedRate: '100–150 g/acre',
      fertilizerNotes: [
        'High K through drip at fruiting — K₂O 80 kg/acre total',
        'Calcium nitrate + boron at first flower cluster',
        'NPK 19:19:19 fertigation weekly first 3 weeks',
      ],
      fertilizerNotesTe: [
        'Fruiting lo K ekkuva drip lo',
        'First flower lo Ca + B',
        'Mudati 3 weeks NPK 19:19:19 drip',
      ],
      sprayNotes: [
        'Early blight from flowering — Mancozeb then Azoxystrobin rotate',
        'Fruit borer — Spinosad on flowers and small fruits',
        'Leaf curl virus — whitefly control with Imidacloprid at nursery',
      ],
      sprayNotesTe: [
        'Early blight flowering nunche Mancozeb',
        'Fruit borer ki Spinosad',
        'Nursery lo whitefly control — leaf curl prevent',
      ],
      diseaseSusceptibility: ['Early blight', 'Fruit borer', 'Leaf curl virus'],
      specialCare: ['Stake and prune for hybrid', 'Drip only — no overhead irrigation'],
      specialCareTe: ['Stake cheyandi hybrid ki', 'Drip use — rain spray vaddu'],
    },
    {
      id: 'pusa_ruby',
      cropId: 'tomato',
      name: 'Pusa Ruby',
      nameTe: 'Pusa Ruby',
      aliases: ['pusa ruby', 'pusaRuby'],
      agmarknetNames: ['Pusa Ruby', 'Pusa-Ruby', 'Tomato Pusa Ruby'],
      duration: '85–100 days',
      grainType: 'Determinate table variety',
      yieldPotential: '100–140 quintals/acre',
      sowingWindow: 'Aug–Sep, Nov–Dec, Jan–Feb',
      harvestWindow: '55–70 days post transplant',
      referenceBaselineQtl: 1750,
      priceNote: 'Open-pollinated table tomato — lower cost seed, moderate mandi rate',
      priceNoteTe: 'OP variety — seed cost taggutundi, madhya mandi rate',
      seedRate: '200–300 g/acre',
      fertilizerNotes: [
        'Basal FYM 5 t/acre + DAP 50 kg at transplant',
        'Side-dress urea 25 kg at flowering if not on drip',
      ],
      fertilizerNotesTe: [
        'FYM basal + DAP transplant time',
        'Flowering lo urea side-dress drip lekapothe',
      ],
      sprayNotes: [
        'Late blight in winter — Metalaxyl + Mancozeb if dew-heavy mornings',
        'Standard fruit borer IPM with pheromone traps',
      ],
      sprayNotesTe: [
        'Winter lo late blight ki Metalaxyl+Mancozeb',
        'Fruit borer IPM pheromone traps tho',
      ],
      diseaseSusceptibility: ['Late blight', 'Fruit borer', 'Septoria leaf spot'],
      specialCare: ['Good for small farmers — seed can be saved (not hybrid)', 'Mulch to reduce soil splash'],
      specialCareTe: ['Small farmers ki baguntundi — seed save cheyochu', 'Mulch use cheyandi'],
    },
    {
      id: 'arka_vikas',
      cropId: 'tomato',
      name: 'Arka Vikas',
      nameTe: 'Arka Vikas',
      aliases: ['arka vikas', 'arkavikas'],
      agmarknetNames: ['Arka Vikas', 'Arka-Vikas', 'Tomato Arka Vikas'],
      duration: '80–95 days',
      grainType: 'Determinate — round firm fruits',
      yieldPotential: '110–150 quintals/acre',
      sowingWindow: 'Year-round except peak summer',
      harvestWindow: '55–65 days post transplant',
      referenceBaselineQtl: 1800,
      priceNote: 'Firm round fruits — preferred by distance markets and vendors',
      priceNoteTe: 'Firm round fruits — doora markets ki baguntundi',
      seedRate: '250–350 g/acre',
      fertilizerNotes: [
        'Balanced NPK with extra K from fruit set — 100:50:80 kg NPK/acre',
        'Foliar calcium at fruit sizing to prevent blossom end rot',
      ],
      fertilizerNotesTe: [
        'Fruit set nunche K ekkuva',
        'Fruit sizing lo calcium foliar — BER prevent',
      ],
      sprayNotes: [
        'Bacterial wilt prone soils — graft on solanum rootstock if available',
        'Preventive Mancozeb every 10 days in humid weather',
      ],
      sprayNotesTe: [
        'Bacterial wilt soils lo grafting consider cheyandi',
        'Humidity ekkuva unte 10 rojula Mancozeb',
      ],
      diseaseSusceptibility: ['Bacterial wilt', 'Early blight', 'Fruit borer'],
      specialCare: ['Harvest at breaker stage for transport', 'Crop rotation — avoid solanaceous overlap'],
      specialCareTe: ['Transport kosam breaker stage harvest', 'Crop rotation follow cheyandi'],
    },
  ],

  maize: [
    {
      id: 'dhm_117',
      cropId: 'maize',
      name: 'DHM 117 (Hybrid)',
      nameTe: 'DHM 117 Hybrid',
      aliases: ['dhm117', 'dhm 117'],
      agmarknetNames: ['DHM 117', 'DHM-117', 'Maize Hybrid'],
      duration: '95–105 days',
      grainType: 'Yellow dent hybrid — dual purpose',
      yieldPotential: '25–32 quintals/acre grain',
      sowingWindow: 'Jun–Jul (Kharif), Jan–Feb (Rabi irrigated)',
      harvestWindow: 'Sep–Oct / Apr–May',
      referenceBaselineQtl: 2000,
      priceNote: 'Popular hybrid — poultry feed demand drives rate; moisture at sale matters',
      priceNoteTe: 'Hybrid — poultry feed demand batti rate; moisture chala mukhyam',
      seedRate: '8–10 kg/acre',
      fertilizerNotes: [
        '120 kg N/acre: 1/3 basal, 1/3 knee-high, 1/3 pre-tasseling',
        'Full DAP 50 kg at sowing; zinc sulphate 10 kg if deficient',
      ],
      fertilizerNotesTe: [
        'N 3 splits: basal, knee-high, tasseling',
        'DAP sowing time, zinc lekapothe 10 kg',
      ],
      sprayNotes: [
        'Fall armyworm — Emamectin whorl application at early infestation',
        'Stem borer — Cartap granules in whorl at 25–30 DAS',
      ],
      sprayNotesTe: [
        'Fall armyworm ki whorl lo Emamectin',
        'Stem borer ki 25–30 DAS whorl granules',
      ],
      diseaseSusceptibility: ['Fall armyworm', 'Stem borer', 'Turcicum leaf blight'],
      specialCare: ['Spacing 60×20 cm for hybrids', 'Ensure pollination — avoid dense planting'],
      specialCareTe: ['60×20 cm spacing', 'Pollination kosam ekkuva dense vaddu'],
    },
    {
      id: 'pmh_1',
      cropId: 'maize',
      name: 'PMH 1 (Hybrid)',
      nameTe: 'PMH 1 Hybrid',
      aliases: ['pmh1', 'pmh 1'],
      agmarknetNames: ['PMH 1', 'PMH-1', 'PMH1'],
      duration: '100–110 days',
      grainType: 'Yellow hybrid — Punjab/Haryana',
      yieldPotential: '28–35 quintals/acre (irrigated)',
      sowingWindow: 'Jun–Jul, Feb (spring irrigated)',
      harvestWindow: 'Oct / May',
      referenceBaselineQtl: 2050,
      priceNote: 'High yield irrigated hybrid — trades near common maize with quality premium for low moisture',
      priceNoteTe: 'Irrigated hybrid yield ekkuva — moisture taggutene premium',
      seedRate: '8 kg/acre',
      fertilizerNotes: [
        '130 kg N/acre under irrigation with 5–6 splits via fertigation if available',
        'Potassium 30 kg/acre at pre-tasseling for stalk strength',
      ],
      fertilizerNotesTe: [
        'Irrigation unte N 130 kg splits lo',
        'Tasseling mundu K 30 kg — stalk strength',
      ],
      sprayNotes: [
        'Maydis leaf blight — Mancozeb at first sign on lower leaves',
        'Aphids at whorl — neem first, Imidacloprid at ETL',
      ],
      sprayNotesTe: [
        'Leaf blight ki Mancozeb',
        'Whorl aphids — mundu neem, tarvata Imidacloprid',
      ],
      diseaseSusceptibility: ['Maydis leaf blight', 'Aphids', 'Stem borer'],
      specialCare: ['Best under assured irrigation', 'Harvest at 20–22% moisture for safe storage'],
      specialCareTe: ['Assured irrigation lo best', '20–22% moisture lo harvest storage ki'],
    },
    {
      id: 'nk_6240',
      cropId: 'maize',
      name: 'NK 6240 (Hybrid)',
      nameTe: 'NK 6240 Hybrid',
      aliases: ['nk6240', 'nk 6240'],
      agmarknetNames: ['NK 6240', 'NK-6240', 'NK6240'],
      duration: '105–115 days',
      grainType: 'Yellow single-cross hybrid',
      yieldPotential: '26–33 quintals/acre',
      sowingWindow: 'Jun–Jul (Kharif)',
      harvestWindow: 'Sep–Oct',
      referenceBaselineQtl: 1980,
      priceNote: 'Widely grown private hybrid — rate follows local mandi maize benchmark',
      priceNoteTe: 'Private hybrid — local maize rate follow avutundi',
      seedRate: '8–10 kg/acre',
      fertilizerNotes: [
        '100 kg N/acre standard; increase to 120 kg on rich soils',
        'FYM 3 t/acre improves water retention on rainfed margins',
      ],
      fertilizerNotesTe: [
        'N 100 kg standard, rich soils lo 120 kg',
        'Rainfed lo FYM 3 t/acre',
      ],
      sprayNotes: [
        'Weed control — Atrazine pre-emergence within 2 DAS on clear soil',
        'Armyworm outbreak — Spinosad + sand whorl application',
      ],
      sprayNotesTe: [
        '2 DAS lopu Atrazine pre-emergence',
        'Armyworm outbreak lo Spinosad whorl lo',
      ],
      diseaseSusceptibility: ['Fall armyworm', 'Weed competition (early)', 'Downy mildew (early season)'],
      specialCare: ['Popular in MP/Maharashtra rainfed belts', 'Thin to one plant per hill'],
      specialCareTe: ['MP/Maharashtra rainfed ki popular', 'Hill lo okati plant matrame'],
    },
  ],

  soybean: [
    {
      id: 'js_335',
      cropId: 'soybean',
      name: 'JS 335',
      nameTe: 'JS 335',
      aliases: ['js335', 'js 335'],
      agmarknetNames: ['JS 335', 'JS-335', 'JS335', 'Soyabean JS 335'],
      duration: '95–105 days',
      grainType: 'Yellow seeded — medium duration',
      yieldPotential: '12–16 quintals/acre',
      sowingWindow: 'Jun–Jul (with monsoon onset)',
      harvestWindow: 'Sep–Oct',
      referenceBaselineQtl: 4250,
      priceNote: 'Most popular MP/Maharashtra variety — benchmark for local mandi soy rate',
      priceNoteTe: 'MP/Maharashtra lo chala popular — soy rate benchmark',
      seedRate: '60–70 kg/acre',
      fertilizerNotes: [
        'Rhizobium seed treatment + PSB — 25 kg/acre DAP basal only',
        'Avoid excess N — nodulation suppress avutundi',
        'Sulfur 20 kg/acre if soil deficient (improves oil%)',
      ],
      fertilizerNotesTe: [
        'Rhizobium + PSB seed treatment, DAP 25 kg basal',
        'Ekkuva N vaddu — nodulation taggutundi',
        'Oil% kosam sulfur lekapothe 20 kg',
      ],
      sprayNotes: [
        'Girdle beetle at pod fill — Quinalphos at ETL',
        'Semilooper — NPV or Emamectin at vegetative if above ETL',
        'Seed treatment with Carbendazim + Thiram for seed rot',
      ],
      sprayNotesTe: [
        'Pod fill lo girdle beetle ki Quinalphos ETL prakaram',
        'Semilooper NPV/Emamectin',
        'Seed treatment Carbendazim + Thiram',
      ],
      diseaseSusceptibility: ['Girdle beetle', 'Semilooper', 'Rust (late season)'],
      specialCare: ['Critical: avoid waterlogging — 24 hr ponding damages crop', 'Harvest at 14–15% moisture'],
      specialCareTe: ['Waterlogging absolutely vaddu', '14–15% moisture lo harvest'],
    },
    {
      id: 'macs_450',
      cropId: 'soybean',
      name: 'MACS 450',
      nameTe: 'MACS 450',
      aliases: ['macs450', 'macs 450'],
      agmarknetNames: ['MACS 450', 'MACS-450', 'MACS450'],
      duration: '100–110 days',
      grainType: 'Bold seeded — higher oil content',
      yieldPotential: '13–17 quintals/acre',
      sowingWindow: 'Jun–Jul',
      harvestWindow: 'Oct',
      referenceBaselineQtl: 4350,
      priceNote: 'Bold grain with good oil — ₹50–150/qtl premium at oil mill procurement',
      priceNoteTe: 'Bold grain oil ekkuva — oil mill lo premium',
      seedRate: '65–75 kg/acre',
      fertilizerNotes: [
        'Rhizobium inoculation mandatory — 20 kg DAP + 15 kg MOP basal',
        'Foliar molybdenum 0.1% if nodulation is poor on acidic soils',
      ],
      fertilizerNotesTe: [
        'Rhizobium must — DAP 20 kg + MOP 15 kg basal',
        'Acidic soils lo molybdenum foliar nodulation ki',
      ],
      sprayNotes: [
        'Pod borer complex — Indoxacarb at flowering if ETL crossed',
        'Charcoal rot prevention — avoid deep planting in cold wet soils',
      ],
      sprayNotesTe: [
        'Pod borer ETL cross aithe Indoxacarb flowering lo',
        'Charcoal rot — cold wet soils lo deep planting vaddu',
      ],
      diseaseSusceptibility: ['Pod borer', 'Charcoal rot', 'Yellow mosaic virus'],
      specialCare: ['Popular in Marathwada/Vidarbha', 'Timely harvest prevents shattering losses'],
      specialCareTe: ['Marathwada/Vidarbha lo popular', 'Late harvest shattering losses'],
    },
    {
      id: 'kds_344',
      cropId: 'soybean',
      name: 'KDS 344',
      nameTe: 'KDS 344',
      aliases: ['kds344', 'kds 344'],
      agmarknetNames: ['KDS 344', 'KDS-344', 'KDS344'],
      duration: '90–100 days',
      grainType: 'Medium bold — early maturing',
      yieldPotential: '11–15 quintals/acre',
      sowingWindow: 'Jun (early) – Jul (normal)',
      harvestWindow: 'Sep–Oct',
      referenceBaselineQtl: 4180,
      priceNote: 'Early variety — useful when sowing delayed; rate near common soybean',
      priceNoteTe: 'Early variety — late sowing ki baguntundi, normal soy rate',
      seedRate: '70–80 kg/acre (late sowing)',
      fertilizerNotes: [
        'Reduced N need — 15 kg DAP basal sufficient with Rhizobium',
        'Increase seed rate 10% if sowing after July 15',
      ],
      fertilizerNotesTe: [
        'Rhizobium tho DAP 15 kg chalu',
        'July 15 tarvata sowing unte seed rate penchandi',
      ],
      sprayNotes: [
        'Whitefly — yellow mosaic vector — Imidacloprid at early vegetative if seen',
        'Rust at R4 stage — Propiconazole if pustules on upper leaves',
      ],
      sprayNotesTe: [
        'Whitefly/yellow mosaic ki Imidacloprid early stage',
        'Rust R4 stage lo Propiconazole',
      ],
      diseaseSusceptibility: ['Yellow mosaic virus', 'Rust', 'Girdle beetle'],
      specialCare: ['Escape terminal drought in short rainy seasons', 'Do not delay harvest past maturity'],
      specialCareTe: ['Short rains lo drought escape', 'Maturity tarvata delay cheyakandi'],
    },
  ],

  chickpea: [
    {
      id: 'jg_11',
      cropId: 'chickpea',
      name: 'JG 11 (Kabuli type)',
      nameTe: 'JG 11 Kabuli',
      aliases: ['jg11', 'jg 11', 'kabuli'],
      agmarknetNames: ['JG 11', 'JG-11', 'Gram JG 11', 'Bengal Gram JG 11'],
      duration: '95–105 days',
      grainType: 'Kabuli — bold cream seeds',
      yieldPotential: '8–12 quintals/acre',
      sowingWindow: 'Oct–Nov (Rabi)',
      harvestWindow: 'Feb–Mar',
      referenceBaselineQtl: 5300,
      priceNote: 'Kabuli gram — ₹200–400/qtl premium over desi gram in export/domestic markets',
      priceNoteTe: 'Kabuli — desi gram kante ekkuva premium rate',
      seedRate: '40–50 kg/acre',
      fertilizerNotes: [
        'Rhizobium + PSB seed treatment — 20 kg DAP basal only',
        'No top-dress N unless pale leaves at flowering (max 15 kg urea)',
        'One irrigation at pre-flowering if no winter rain',
      ],
      fertilizerNotesTe: [
        'Rhizobium + PSB, DAP 20 kg basal',
        'Flowering lo pale leaves unte matrame urea',
        'Pre-flowering oka neeru avasaramaina',
      ],
      sprayNotes: [
        'Wilt complex — Trichoderma seed treatment + avoid sowing in Fusarium sick plots',
        'Pod borer — HaNPV or Indoxacarb at 50% flowering if ETL',
      ],
      sprayNotesTe: [
        'Wilt ki Trichoderma seed treatment',
        'Pod borer 50% flowering lo HaNPV/Indoxacarb',
      ],
      diseaseSusceptibility: ['Fusarium wilt', 'Pod borer', 'Ascochyta blight'],
      specialCare: ['Deep well-drained soil essential', 'Do not over-irrigate — sensitive to waterlogging'],
      specialCareTe: ['Well-drained soil must', 'Ekkuva neeru vaddu'],
    },
    {
      id: 'gng_1581',
      cropId: 'chickpea',
      name: 'GNG 1581 (Desi)',
      nameTe: 'GNG 1581 Desi',
      aliases: ['gng1581', 'gng 1581'],
      agmarknetNames: ['GNG 1581', 'GNG-1581', 'GNG1581'],
      duration: '100–110 days',
      grainType: 'Desi — small brown seeds',
      yieldPotential: '10–14 quintals/acre',
      sowingWindow: 'Oct–Nov',
      harvestWindow: 'Feb–Mar',
      referenceBaselineQtl: 5150,
      priceNote: 'High-yielding desi — dal mill standard; trades near MSP',
      priceNoteTe: 'Desi high yield — dal mills ki standard, MSP daggara',
      seedRate: '35–45 kg/acre',
      fertilizerNotes: [
        'Basal DAP 20 kg/acre with Rhizobium culture',
        'Sulfur 20 kg/acre improves protein in desi types',
      ],
      fertilizerNotesTe: [
        'DAP 20 kg + Rhizobium basal',
        'Protein kosam sulfur 20 kg',
      ],
      sprayNotes: [
        'Blights in humid Jan — Mancozeb + Carbendazim rotate if spots on stems',
        'Cutworm at seedling — Chlorpyriphos drench if cut plants seen',
      ],
      sprayNotesTe: [
        'Jan humidity lo blight ki Mancozeb rotate',
        'Cutworm seedlings ki Chlorpyriphos drench',
      ],
      diseaseSusceptibility: ['Ascochyta blight', 'Cutworm', 'Pod borer'],
      specialCare: ['Popular in Rajasthan/Gujarat', 'Seed treatment with Trichoderma recommended'],
      specialCareTe: ['Rajasthan/Gujarat lo popular', 'Trichoderma seed treatment'],
    },
    {
      id: 'pusa_362',
      cropId: 'chickpea',
      name: 'Pusa 362 (Desi)',
      nameTe: 'Pusa 362 Desi',
      aliases: ['pusa362', 'pusa 362'],
      agmarknetNames: ['Pusa 362', 'Pusa-362', 'Pusa362'],
      duration: '105–115 days',
      grainType: 'Desi — medium duration',
      yieldPotential: '9–13 quintals/acre',
      sowingWindow: 'Oct–Nov',
      harvestWindow: 'Mar',
      referenceBaselineQtl: 5080,
      priceNote: 'North India desi standard — rate follows NAFED/MSP procurement norms',
      priceNoteTe: 'North India desi — MSP procurement rate follow avutundi',
      seedRate: '40–50 kg/acre',
      fertilizerNotes: [
        '20 kg DAP at sowing — no N if nodulation good',
        'Single light irrigation at flowering if soil dry',
      ],
      fertilizerNotesTe: [
        'Sowing lo DAP 20 kg — N avasaram ledu nodulation unte',
        'Flowering dry unte oka light neeru',
      ],
      sprayNotes: [
        'Wilt — sow only in well-drained fields; seed treat with Carbendazim 2 g/kg',
        'Helicoverpa at pod stage — HaNPV 250 LE/acre evening spray',
      ],
      sprayNotesTe: [
        'Wilt sick fields lo sow vaddu, seed Carbendazim treatment',
        'Pod stage Helicoverpa ki HaNPV evening spray',
      ],
      diseaseSusceptibility: ['Wilt', 'Helicoverpa (pod borer)', 'Root rot'],
      specialCare: ['Drought tolerant — minimal irrigation philosophy', 'Harvest when pods turn straw-colour'],
      specialCareTe: ['Drought tolerant — minimum neeru', 'Pods straw colour ayyaka harvest'],
    },
  ],

  sugarcane: [
    {
      id: 'co_86032',
      cropId: 'sugarcane',
      name: 'Co 86032',
      nameTe: 'Co 86032',
      aliases: ['co86032', 'co 86032', '86032'],
      agmarknetNames: ['Co 86032', 'Co-86032', 'CO 86032', 'Sugarcane Co 86032'],
      duration: '10–12 months crop cycle',
      grainType: 'Mid-late — high sucrose',
      yieldPotential: '350–450 quintals/acre cane',
      sowingWindow: 'Oct–Nov (adsali) or Feb–Mar (spring)',
      harvestWindow: '10–12 months after planting',
      referenceBaselineQtl: 325,
      priceNote: 'SAP/FRP linked — rate set by state; sucrose recovery % drives final payment',
      priceNoteTe: 'SAP/FRP prakaram rate — sucrose recovery batti final pay',
      seedRate: '40,000 two-bud setts/acre',
      fertilizerNotes: [
        '250:115:115 kg NPK/acre in splits: 25% basal, 25% at 45 DAP, 25% at 90 DAP, 25% at 180 DAP',
        'Trash mulching after each fertilizer application',
        'Apply zinc 25 kg/acre if ratoon crop shows yellowing',
      ],
      fertilizerNotesTe: [
        'NPK 250:115:115 splits lo — 45, 90, 180 DAP',
        'Fertilizer tarvata trash mulching',
        'Ratoon lo zinc lekapothe 25 kg',
      ],
      sprayNotes: [
        'Early shoot borer — Chlorantraniliprole at 30–45 DAP',
        'Top borer — Cartap at dead-heart stage in main shoot',
        'Pyrilla — Dimethoate if sooty mould on leaves',
      ],
      sprayNotesTe: [
        'Early shoot borer 30–45 DAP Chlorantraniliprole',
        'Top borer dead-heart Cartap',
        'Pyrilla sooty mould unte Dimethoate',
      ],
      diseaseSusceptibility: ['Early shoot borer', 'Top borer', 'Red rot', 'Smut'],
      specialCare: ['Popular across South India', 'Ratoon management: crush stubble, apply trash mulch + 50 kg urea'],
      specialCareTe: ['South India lo popular', 'Ratoon: stubble crush, trash mulch + urea'],
    },
    {
      id: 'com_0265',
      cropId: 'sugarcane',
      name: 'CoM 0265',
      nameTe: 'CoM 0265',
      aliases: ['com0265', 'com 0265', 'co 0265'],
      agmarknetNames: ['CoM 0265', 'CoM-0265', 'COM 0265', 'Co 0265'],
      duration: '11–13 months crop cycle',
      grainType: 'Early-mid — good ratooner',
      yieldPotential: '320–400 quintals/acre cane',
      sowingWindow: 'Oct–Nov or Feb–Mar',
      harvestWindow: '11–13 months after planting',
      referenceBaselineQtl: 318,
      priceNote: 'Good ratoon performer — farmers value total 2–3 crop cycle economics over single crop rate',
      priceNoteTe: 'Ratoon baguntundi — 2–3 crops economics mukhyam single rate kante',
      seedRate: '38,000–42,000 setts/acre',
      fertilizerNotes: [
        'Similar NPK to Co 86032 but reduce N 10% on ratoon crop',
        'Silicon + potassium at grand growth phase (120–180 DAP)',
      ],
      fertilizerNotesTe: [
        'Co 86032 laga NPK — ratoon lo N 10% tagginchandi',
        'Grand growth (120–180 DAP) lo silicon + K',
      ],
      sprayNotes: [
        'Internode borer — apply granules in leaf whorl at 4–5 month stage',
        'Red rot — avoid setts from infected fields; hot water treatment 52°C 30 min',
      ],
      sprayNotesTe: [
        'Internode borer 4–5 month whorl granules',
        'Red rot infected fields setts vaddu, hot water treatment',
      ],
      diseaseSusceptibility: ['Internode borer', 'Red rot', 'Grassy shoot disease'],
      specialCare: ['Excellent ratoon yields for 2 cycles', 'Deep planting in furrows with bud facing sideways'],
      specialCareTe: ['Ratoon 2 cycles yield bagundi', 'Furrow lo bud side planting'],
    },
  ],
};
